DROP TRIGGER IF EXISTS trg_tb_tombstone ON calendar.time_blocks;
DROP TRIGGER IF EXISTS trg_tb_bump ON calendar.time_blocks;
DROP TABLE IF EXISTS calendar.time_block_tombstones;
DROP FUNCTION IF EXISTS calendar.tb_tombstone();
DROP FUNCTION IF EXISTS calendar.tb_bump();
ALTER TABLE calendar.time_blocks DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS calendar.tb_change_seq;
DROP TRIGGER IF EXISTS trg_att_bump ON calendar.attendees;
DROP FUNCTION IF EXISTS calendar.att_bump_event();
DROP TRIGGER IF EXISTS trg_ev_tombstone ON calendar.events;
DROP TRIGGER IF EXISTS trg_ev_bump ON calendar.events;
DROP TABLE IF EXISTS calendar.event_tombstones;
DROP FUNCTION IF EXISTS calendar.ev_tombstone();
DROP FUNCTION IF EXISTS calendar.ev_bump();
ALTER TABLE calendar.events DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS calendar.ev_change_seq;
DROP TRIGGER IF EXISTS trg_cal_tombstone ON calendar.calendars;
DROP TRIGGER IF EXISTS trg_cal_bump ON calendar.calendars;
DROP TABLE IF EXISTS calendar.calendar_tombstones;
DROP FUNCTION IF EXISTS calendar.cal_tombstone();
DROP FUNCTION IF EXISTS calendar.cal_bump();
ALTER TABLE calendar.calendars DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS calendar.cal_change_seq;
